### ISSUE TITLE
Meilleure gestion des erreurs lorsqu'on tente d'inscrire un joueur déjà dans une équipe

### ISSUE THREAD

**Issue by JulienChavee** [JulienChavee/bruminator2.0#11]
Avoir un message signalant ceci.
Si le joueur existe mais dans aucune équipe, aucun message, on assigne l'équipe à ce joueur

**Comment by Jujuwar** [comment]
Attention au cas où un utilisateur souhaite inverser le remplaçant et le titulaire (peut-être proposer directement une option pour le faire ?)

**Comment by Jujuwar** [comment]
Séparation des tâches :

- Joueurs sans équipe et inversion titulaire/remplacant : #56)
- Message d'erreur si joueur existant et dans une équipe : #11)
