### ISSUE TITLE
Ajout d'un nouveau joueur - Modification d'équipe - Erreur lors de la vérification

### ISSUE THREAD

**Issue by JulienChavee** [JulienChavee/bruminator2.0#17]
Lors de l'édition d'un joueur, que l'on coche "nouveau joueur", l'ancien joueur n'est pas correctement supprimé de l'équipe

**Comment by Jujuwar** [comment]
Attention également au cas du remplaçant

**Comment by Jujuwar** [comment]
Lié au fait que l'on effectue d'un check de la composition
